# Generated by Django 5.2.1 on 2025-07-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShawarmaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shawarmas/images/')),
                ('shawarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='burger.shawarma')),
            ],
        ),
    ]
