# Generated by Django 5.2.1 on 2025-07-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0002_shawarmaimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shawarma',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shawarmaimage',
            name='shawarma',
        ),
        migrations.DeleteModel(
            name='ShawarmaCategory',
        ),
        migrations.DeleteModel(
            name='Shawarma',
        ),
        migrations.DeleteModel(
            name='ShawarmaImage',
        ),
    ]
